/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: never
        }
      }
    }
  }
  "/api/elasticsearch/health": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: never
        }
        /** @description Internal Server Error */
        500: {
          content: never
        }
      }
    }
  }
  "/api/recipes": {
    post: {
      requestBody?: {
        content: {
          "application/json": {
            /** @example any */
            recipe?: unknown
          }
        }
      }
      responses: {
        /** @description Created */
        201: {
          content: never
        }
        /** @description Internal Server Error */
        500: {
          content: never
        }
      }
    }
  }
  "/api/recipes/{id}": {
    delete: {
      parameters: {
        path: {
          id: string
        }
      }
      responses: {
        /** @description OK */
        200: {
          content: never
        }
        /** @description Internal Server Error */
        500: {
          content: never
        }
      }
    }
  }
  "/api/recipes/search": {
    post: {
      requestBody?: {
        content: {
          "application/json": {
            /** @example any */
            materials?: unknown
            /** @example any */
            dish?: unknown
            /** @example any */
            cookingTime?: unknown
          }
        }
      }
      responses: {
        /** @description OK */
        200: {
          content: never
        }
        /** @description Not Found */
        404: {
          content: never
        }
        /** @description Internal Server Error */
        500: {
          content: never
        }
      }
    }
  }
  "/api/recipes/search/keywords": {
    post: {
      requestBody?: {
        content: {
          "application/json": {
            /** @example any */
            keywords?: unknown
          }
        }
      }
      responses: {
        /** @description OK */
        200: {
          content: never
        }
        /** @description Not Found */
        404: {
          content: never
        }
        /** @description Internal Server Error */
        500: {
          content: never
        }
      }
    }
  }
  "/api/recipes/search/query": {
    post: {
      requestBody?: {
        content: {
          "application/json": {
            /** @example any */
            query?: unknown
          }
        }
      }
      responses: {
        /** @description OK */
        200: {
          content: never
        }
        /** @description Not Found */
        404: {
          content: never
        }
        /** @description Internal Server Error */
        500: {
          content: never
        }
      }
    }
  }
  "/api/recipes/search/old": {
    post: {
      requestBody?: {
        content: {
          "application/json": {
            /** @example any */
            searchInfo?: unknown
          }
        }
      }
      responses: {
        /** @description OK */
        200: {
          content: never
        }
        /** @description Internal Server Error */
        500: {
          content: never
        }
      }
    }
  }
  "/api/searchRecipes/keywords": {
    post: {
      requestBody?: {
        content: {
          "application/json": {
            /** @example any */
            keywords?: unknown
          }
        }
      }
      responses: {
        /** @description OK */
        200: {
          content: never
        }
        /** @description Internal Server Error */
        500: {
          content: never
        }
      }
    }
  }
  "/api/users/favorites": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: never
        }
        /** @description Unauthorized */
        401: {
          content: never
        }
        /** @description Internal Server Error */
        500: {
          content: never
        }
      }
    }
    post: {
      requestBody?: {
        content: {
          "application/json": {
            /** @example any */
            recipeId?: unknown
          }
        }
      }
      responses: {
        /** @description OK */
        200: {
          content: never
        }
        /** @description Bad Request */
        400: {
          content: never
        }
        /** @description Unauthorized */
        401: {
          content: never
        }
        /** @description Internal Server Error */
        500: {
          content: never
        }
      }
    }
  }
  "/api/users/favorites/{id}": {
    delete: {
      parameters: {
        path: {
          id: string
        }
      }
      responses: {
        /** @description OK */
        200: {
          content: never
        }
        /** @description Unauthorized */
        401: {
          content: never
        }
        /** @description Internal Server Error */
        500: {
          content: never
        }
      }
    }
  }
  "/api/users": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: never
        }
        /** @description Unauthorized */
        401: {
          content: never
        }
        /** @description Not Found */
        404: {
          content: never
        }
        /** @description Internal Server Error */
        500: {
          content: never
        }
      }
    }
  }
  "/api/recipes/new": {
    post: {
      requestBody?: {
        content: {
          "application/json": {
            /** @example any */
            title?: unknown
            /** @example any */
            description?: unknown
            /** @example any */
            totalCookingTime?: unknown
            /** @example any */
            materials?: unknown
            /** @example any */
            materialsConverted?: unknown
            /** @example any */
            sourceUrl?: unknown
            /** @example any */
            foodImageUrl?: unknown
            /** @example any */
            dish?: unknown
          }
        }
      }
      responses: {
        /** @description Created */
        201: {
          content: never
        }
        /** @description Bad Request */
        400: {
          content: never
        }
        /** @description Unauthorized */
        401: {
          content: never
        }
        /** @description Internal Server Error */
        500: {
          content: never
        }
      }
    }
  }
  "/api/recipes/scrape": {
    post: {
      requestBody?: {
        content: {
          "application/json": {
            /** @example any */
            sourceUrl?: unknown
          }
        }
      }
      responses: {
        /** @description OK */
        200: {
          content: never
        }
        /** @description Bad Request */
        400: {
          content: never
        }
        /** @description Internal Server Error */
        500: {
          content: never
        }
      }
    }
  }
}

export type webhooks = Record<string, never>

export interface components {
  schemas: {
    Recipe: {
      id: number
      title: string
      description: string
      totalCookingTime: number
      materials: string[]
      keywords: string[]
      sourceUrl: string
      foodImageUrl: string
      dish: string
      category?: string
      cuisine?: string
      /** Format: date-time */
      createdAt: string
    }
    SearchInfo: {
      ingredients: string[]
      dish?: string | null
      cookingTime?: string | null
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}

export type $defs = Record<string, never>

export type external = Record<string, never>

export type operations = Record<string, never>
