name: Build Test

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Setup Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: latest
      #     cache: npm

      # - name: Install dependencies for backend
      #   run: cd backend && npm ci
      #   shell: bash

      # - name: Install dependencies for frontend
      #   run: cd frontend && npm ci
      #   shell: bash

      # - name: Build backend
      #   run: cd backend && npm run build
      #   shell: bash

      # - name: Build frontend
      #   run: cd frontend && npm run build
      #   shell: bash
